# Based on the "trust" template v0.1.2
# https://github.com/japaric/trust/tree/v0.1.2

dist: trusty
language: rust
services: docker
sudo: required

env:
  global:
    - CRATE_NAME=autojump

matrix:
  include:
    # OSX
    # HACK: open-source jobs on OSX take VERY long time just to start, so just
    # get up earlier like when you're attending a live or so
    - env: TARGET=i686-apple-darwin
      os: osx
    - env: TARGET=x86_64-apple-darwin
      os: osx

    # Android
    - env: TARGET=aarch64-linux-android DISABLE_TESTS=1
    - env: TARGET=arm-linux-androideabi DISABLE_TESTS=1
    - env: TARGET=armv7-linux-androideabi DISABLE_TESTS=1
    - env: TARGET=i686-linux-android DISABLE_TESTS=1
    - env: TARGET=x86_64-linux-android DISABLE_TESTS=1

    # Linux
    - env: TARGET=aarch64-unknown-linux-gnu
    - env: TARGET=arm-unknown-linux-gnueabi
    - env: TARGET=armv7-unknown-linux-gnueabihf
    - env: TARGET=i686-unknown-linux-musl
    - env: TARGET=mips-unknown-linux-gnu
    - env: TARGET=mips64-unknown-linux-gnuabi64
    - env: TARGET=mips64el-unknown-linux-gnuabi64
    - env: TARGET=mipsel-unknown-linux-gnu
    - env: TARGET=powerpc-unknown-linux-gnu
    - env: TARGET=powerpc64-unknown-linux-gnu
    - env: TARGET=powerpc64le-unknown-linux-gnu
    - env: TARGET=s390x-unknown-linux-gnu DISABLE_TESTS=1
    - env: TARGET=x86_64-unknown-linux-musl

    # *BSD
    - env: TARGET=i686-unknown-freebsd DISABLE_TESTS=1
    - env: TARGET=x86_64-unknown-freebsd DISABLE_TESTS=1
    - env: TARGET=x86_64-unknown-netbsd DISABLE_TESTS=1

  # netbsd currently doesn't build (because of nix-0.9.0)
  env:  # important: https://docs.travis-ci.com/user/customizing-the-build/#rows-that-are-allowed-to-fail
  allow_failures:
    - env: TARGET=x86_64-unknown-netbsd DISABLE_TESTS=1

before_install:
  - set -e
  - rustup self update

install:
  - sh ci/install.sh
  - source ~/.cargo/env || true

script:
  - bash ci/script.sh

after_script: set +e

before_deploy:
  - sh ci/before_deploy.sh

deploy:
  api_key:
    secure: G3d3zoQ5NA+fLIXOMxL1TuYZIN76yiEQQ6AEyQwV9YNKvDCuqDy+Ls6c2RqSdDBOe+jdqMO8kCQGhgj4u+YIx8zlkzO5WjepQk9a/4VeAHGRsLuCvvTq1J9zqDxw7s6klZBvDJM9EJboviIguDJQn+5/jwGqYczw1Qq6JzXpo5AfTg5O9UcDIRgZlt4LXpHgNvM4tIFD6RnFoeCxzIPloNoKDnqB3Ebxcf1vD/xhXQZR9zlFE7Zq0nmmY2C+nvwVfEzvBaKdiSrk2ZDfw1jhPdQTHcIOwmUUSfhRIOjQvmVtSojDy+p8wZ2O0Tvopuj//XrL3kGo9tDdeFpht4atF92OesYit5ZoutCJZgcoOQHr/yKt0lVcCqYihh7voeWZ4fDUXXbwI4jpn6uXE6P60s5u9KV64XkwQJanZoz/Pn3KAZRzvmtbjQbS7xQ4gaU1on0KJW4ETesMta4sCKDT8VCt8umZGHJOvneCFChOdsuVy+oUXHmpIiijVwprm+pgN/IQgrVWX9uVNTksU4pJ9XpcJudjQ+2aVXRzeuTuEuP6EArcc12DMsoaTbvjEyVy5jLcW4XBF5vMKvNZ9ydUQEAGBEkSeyR1QR5MpsBCZEz49EY8dqPzPwzbkoU3nh+rPKSD9FxQL+IRlqw6m7oP9worzbpW081vVzLBiTscmOg=

  file_glob: true
  file: $CRATE_NAME-$TRAVIS_TAG-$TARGET.*
  on:
    condition: $TRAVIS_RUST_VERSION = nightly
    tags: true
  provider: releases
  skip_cleanup: true

cache: cargo
before_cache:
  # Travis can't cache files that are not readable by "others"
  - chmod -R a+r $HOME/.cargo

branches:
  only:
    # release tags
    - /^\d+\.\d+\.\d+.*$/
    - master

notifications:
  email:
    on_success: never
