[package]
name = "autojump"
version = "0.3.0"
authors = ["Wang Xuerui <git@xen0n.name>"]
description = "A Rust port and drop-in replacement of autojump"
repository = "https://github.com/xen0n/autojump-rs"
readme = "README.md"
license = "GPL-3.0+"
include = ["src/**/*.rs", "Cargo.toml"]


[features]
default = []
nightly = []


[dependencies]
# atomicwrites = "0.1.3"
atomicwrites = { git = "https://github.com/xen0n/rust-atomicwrites", branch = "feature/update-nix" }
docopt = "0.8.1"
regex = "0.2"
serde = "1.0.19"
serde_derive = "1.0.19"
strsim = "0.6"
