[package]
name = "autojump"
version = "0.1.0"
authors = ["Wang Xuerui <git@xen0n.name>"]
description = "A Rust port and drop-in replacement of autojump"
repository = "https://github.com/xen0n/autojump-rs"
readme = "README.md"
license = "GPL-3.0+"
include = ["src/*.rs", "Cargo.toml", "build.rs"]
build = "build.rs"


[dependencies]
atomicwrites = "0.0.14"
docopt = "0.6"
regex = "0.1"
rustc-serialize = "0.3"
strsim = "0.5"


[build-dependencies]
walkdir = "0.1"
